"""
generator.py
============

Walks the AST produced by parser.py and emits valid JavaScript text.

Design decision: one `generate_<category>` method per node category,
dispatched via a dict (`self.dispatch`) rather than a long if/elif
chain. This mirrors the Dictionary's data-driven philosophy -- adding
a category is a matter of adding one method + one dispatch entry, not
threading a new branch through a monolithic function.

The Generator consults dictionary.py for the underlying JS binding of
each keyword (e.g. 'click' -> 'click', 'hover' -> 'mouseenter') rather
than hardcoding those mappings itself.

Smart Objects (card_center_screen, card_glide, etc.) currently compile
to a small inline <style> block injected via JS, since VTC v1 has no
separate CSS output file yet. See context.md -> "Planned graphics/CSS
layer" for how this will evolve into first-class CSS generation.
"""

from __future__ import annotations
from .ast_nodes import (
    Node, ImportNode, ButtonNode, FormNode, CardNode, DropdownNode,
    NavigationNode, AnimationNode, ApiNode, ModalNode, HistoryNode,
    TransferNode, ReceiveNode, WalletNode, ValidationNode, NewsletterNode,
    GenericNode,
)
from . import dictionary
from .errors import IntentError

# CSS fragments for smart-object modifiers. Keeping this as a small
# lookup table (data-driven, same spirit as dictionary.py) makes it
# trivial to extend when the graphics module lands.
SMART_OBJECT_CSS: dict[str, str] = {
    "card_center_screen": (
        "position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);"
    ),
    "card_middle": "margin-top:auto;margin-bottom:auto;",
    "card_bottom": "position:fixed;bottom:0;left:0;right:0;",
    "card_float": "animation:vtc-float 3s ease-in-out infinite;",
    "card_glide": "animation:vtc-glide 0.6s ease-out;",
    "card_flip": "transition:transform 0.6s;transform-style:preserve-3d;",
}

SMART_OBJECT_KEYFRAMES = """
@keyframes vtc-float { 0%,100% { transform:translateY(0);} 50% { transform:translateY(-10px);} }
@keyframes vtc-glide { from { opacity:0; transform:translateX(-30px);} to { opacity:1; transform:translateX(0);} }
""".strip()


class Generator:
    """Generates JavaScript source from a VTC AST."""

    def __init__(self):
        self.lines: list[str] = []
        self._needs_keyframes = False
        self.dispatch = {
            "button": self.generate_button,
            "form": self.generate_form,
            "card": self.generate_card,
            "dropdown": self.generate_dropdown,
            "navigation": self.generate_navigation,
            "smart_object": self.generate_smart_object,
            "api": self.generate_api,
            "modal": self.generate_modal,
            "history": self.generate_history,
            "transfer": self.generate_transfer,
            "receive": self.generate_receive,
            "wallet": self.generate_wallet,
            "validation": self.generate_validation,
            "newsletter": self.generate_newsletter,
            "generic": self.generate_generic,
        }

    # ------------------------------------------------------------------
    def generate(self, nodes: list[Node | ImportNode]) -> str:
        self.lines = []
        self._needs_keyframes = False

        self.lines.append("// Generated by the VTC compiler. Do not edit directly.")
        self.lines.append('"use strict";')
        self.lines.append("")

        for node in nodes:
            if isinstance(node, ImportNode):
                self._generate_import(node)
                continue

            handler = self.dispatch.get(node.category, self.generate_generic)
            handler(node)
            self.lines.append("")

        if self._needs_keyframes:
            self._inject_keyframes()

        return "\n".join(self.lines).rstrip() + "\n"

    # ------------------------------------------------------------------
    def _generate_import(self, node: ImportNode) -> None:
        if node.module == "graphics":
            self.lines.append(
                "// import(graphics) -- reserved for the future VTC graphics module."
            )
            self.lines.append(
                "// This module will compile graphical-language blocks into CSS."
            )
        else:
            self.lines.append(f"// import({node.module}) -- unrecognized future module, ignored.")

    def _inject_keyframes(self) -> None:
        self.lines.append("// Smart-object keyframe animations")
        self.lines.append("(function injectVtcKeyframes() {")
        self.lines.append("  const style = document.createElement('style');")
        css = SMART_OBJECT_KEYFRAMES.replace("\n", " ")
        self.lines.append(f"  style.textContent = {css!r};")
        self.lines.append("  document.head.appendChild(style);")
        self.lines.append("})();")

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------
    def _resolve_event(self, vtc_event: str, line: int) -> str:
        js_event = dictionary.lookup_event(vtc_event)
        if js_event is None:
            from .errors import unknown_keyword_error
            raise unknown_keyword_error(vtc_event, dictionary.all_events(), line=line)
        return js_event

    def _apply_smart_object_modifiers(self, node: Node, var_name: str) -> None:
        """Apply any card_* smart-object modifiers found on a node."""
        for stmt in node.statements:
            if stmt.keyword in SMART_OBJECT_CSS:
                css = SMART_OBJECT_CSS[stmt.keyword]
                self.lines.append(f"if ({var_name}) {var_name}.style.cssText += {css!r};")
                if stmt.keyword in ("card_float", "card_glide"):
                    self._needs_keyframes = True

    # ------------------------------------------------------------------
    # Category generators
    # ------------------------------------------------------------------
    def generate_button(self, node: ButtonNode) -> None:
        target = node.get("button_element")
        if target is None:
            raise IntentError("A (button_element=...) block must name a target.", line=node.line)
        var_name = f"btn_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")

        event = node.get("event_listener")
        action = node.get("action")
        if event:
            js_event = self._resolve_event(event, node.line)
            handler_body = f"{action}();" if action else "/* no action declared */"
            self.lines.append(f"if ({var_name}) {{")
            self.lines.append(f"  {var_name}.addEventListener('{js_event}', function() {{ {handler_body} }});")
            self.lines.append("}")

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_form(self, node: FormNode) -> None:
        target = node.get("form_element") or node.get("input_element")
        if target is None:
            raise IntentError("A form block must name a (form_element=...) or (input_element=...).", line=node.line)
        var_name = f"form_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")

        event = node.get("event_listener")
        action = node.get("action")
        if event:
            js_event = self._resolve_event(event, node.line)
            handler_body = f"{action}(event);" if action else "/* no action declared */"
            self.lines.append(f"if ({var_name}) {{")
            self.lines.append(f"  {var_name}.addEventListener('{js_event}', function(event) {{ {handler_body} }});")
            self.lines.append("}")

        for value in node.get_all("validate_input"):
            if value:
                self.lines.append(
                    f"function vtc_validate_{value}(val) {{ "
                    f"return val !== undefined && val !== null && String(val).trim().length > 0; }}"
                )

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_card(self, node: CardNode) -> None:
        target = node.get("card_element")
        if target is None:
            raise IntentError("A card block must name a (card_element=...).", line=node.line)
        var_name = f"card_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")
        self._apply_smart_object_modifiers(node, var_name)

        event = node.get("event_listener")
        action = node.get("action")
        if event:
            js_event = self._resolve_event(event, node.line)
            handler_body = f"{action}();" if action else "/* no action declared */"
            self.lines.append(f"if ({var_name}) {{")
            self.lines.append(f"  {var_name}.addEventListener('{js_event}', function() {{ {handler_body} }});")
            self.lines.append("}")

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_dropdown(self, node: DropdownNode) -> None:
        target = node.get("dropdown_element")
        if target is None:
            raise IntentError("A dropdown block must name a (dropdown_element=...).", line=node.line)
        var_name = f"dropdown_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")

        event = node.get("event_listener") or "click"
        js_event = self._resolve_event(event, node.line)
        self.lines.append(f"if ({var_name}) {{")
        self.lines.append(
            f"  {var_name}.addEventListener('{js_event}', function() {{ "
            f"{var_name}.classList.toggle('open'); }});"
        )
        self.lines.append("}")

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_navigation(self, node: NavigationNode) -> None:
        target = node.get("nav_element")
        var_name = f"nav_{target}" if target else "nav_root"
        if target:
            self.lines.append(f"const {var_name} = document.getElementById('{target}');")

        fetch_page = node.get("fetch_page")
        if fetch_page:
            self.lines.append(f"async function vtc_navigate_{fetch_page}() {{")
            self.lines.append(f"  const response = await fetch('/pages/{fetch_page}');")
            self.lines.append("  const html = await response.text();")
            self.lines.append("  document.querySelector('main').innerHTML = html;")
            self.lines.append(f"  history.pushState({{}}, '', '/{fetch_page}');")
            self.lines.append("}")

        event = node.get("event_listener")
        action = node.get("action")
        if event and target:
            js_event = self._resolve_event(event, node.line)
            handler_body = f"{action}();" if action else (
                f"vtc_navigate_{fetch_page}();" if fetch_page else "/* no action declared */"
            )
            self.lines.append(f"if ({var_name}) {{")
            self.lines.append(f"  {var_name}.addEventListener('{js_event}', function() {{ {handler_body} }});")
            self.lines.append("}")

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_smart_object(self, node: AnimationNode) -> None:
        # Standalone smart-object block with no explicit target -- apply
        # to whatever element the statement set implies, defaulting to body.
        target = node.get("card_element") or "body"
        var_name = "smart_" + target if target != "body" else "document.body"
        if target != "body":
            self.lines.append(f"const {var_name} = document.getElementById('{target}');")
        self._apply_smart_object_modifiers(node, var_name)

    def generate_api(self, node: ApiNode) -> None:
        endpoint = node.get("request_from_api")
        page = node.get("fetch_page")

        if endpoint:
            fn_name = "vtc_api_" + endpoint.strip("/").replace("/", "_")
            self.lines.append(f"async function {fn_name}(payload) {{")
            self.lines.append(f"  const response = await fetch('{endpoint}', {{")
            self.lines.append("    method: payload ? 'POST' : 'GET',")
            self.lines.append("    headers: { 'Content-Type': 'application/json' },")
            self.lines.append("    body: payload ? JSON.stringify(payload) : undefined,")
            self.lines.append("  });")
            self.lines.append("  return response.json();")
            self.lines.append("}")
        elif page:
            fn_name = f"vtc_fetch_page_{page}"
            self.lines.append(f"async function {fn_name}() {{")
            self.lines.append(f"  const response = await fetch('/pages/{page}');")
            self.lines.append("  return response.text();")
            self.lines.append("}")
        else:
            raise IntentError(
                "An api block must declare (request_from_api=...) or (fetch_page=...).",
                line=node.line,
            )

    def generate_modal(self, node: ModalNode) -> None:
        target = node.get("modal_element")
        if target is None:
            raise IntentError("A modal block must name a (modal_element=...).", line=node.line)
        var_name = f"modal_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")

        event = node.get("event_listener")
        action = node.get("action")
        if event:
            js_event = self._resolve_event(event, node.line)
            handler_body = f"{action}();" if action else f"{var_name}.classList.add('open');"
            self.lines.append(f"if ({var_name}) {{")
            self.lines.append(f"  {var_name}.addEventListener('{js_event}', function() {{ {handler_body} }});")
            self.lines.append("}")

        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_history(self, node: HistoryNode) -> None:
        if node.has("push_history"):
            path = node.get("push_history")
            self.lines.append(f"history.pushState({{}}, '', '{path}');")
        if node.has("go_back"):
            self.lines.append("history.back();")

    def generate_transfer(self, node: TransferNode) -> None:
        amount = node.get("transfer_amount")
        self.lines.append("function vtc_transfer(fromAccount, toAccount, amount) {")
        self.lines.append("  // Frontend-only stub: wire this up to a real API call.")
        self.lines.append(
            f"  return {{ type: 'transfer', amount: amount ?? {amount or 0}, from: fromAccount, to: toAccount }};"
        )
        self.lines.append("}")

    def generate_receive(self, node: ReceiveNode) -> None:
        amount = node.get("receive_amount")
        self.lines.append("function vtc_receive(fromAccount, amount) {")
        self.lines.append("  // Frontend-only stub: wire this up to a real API call.")
        self.lines.append(
            f"  return {{ type: 'receive', amount: amount ?? {amount or 0}, from: fromAccount }};"
        )
        self.lines.append("}")

    def generate_wallet(self, node: WalletNode) -> None:
        target = node.get("wallet_element")
        if target is None:
            raise IntentError("A wallet block must name a (wallet_element=...).", line=node.line)
        var_name = f"wallet_{target}"
        self.lines.append(f"const {var_name} = document.getElementById('{target}');")
        self._apply_smart_object_modifiers(node, var_name)
        for stmt in node.statements:
            self._apply_misc_statement(stmt, var_name)

    def generate_validation(self, node: ValidationNode) -> None:
        rule = node.get("validate_input")
        if rule:
            self.lines.append(
                f"function vtc_validate_{rule}(val) {{ "
                f"return val !== undefined && val !== null && String(val).trim().length > 0; }}"
            )

    def generate_newsletter(self, node: NewsletterNode) -> None:
        endpoint = node.get("newsletter_signup") or "/newsletter/signup"
        self.lines.append("async function vtc_newsletter_signup(email) {")
        self.lines.append(f"  const response = await fetch('{endpoint}', {{")
        self.lines.append("    method: 'POST',")
        self.lines.append("    headers: { 'Content-Type': 'application/json' },")
        self.lines.append("    body: JSON.stringify({ email }),")
        self.lines.append("  });")
        self.lines.append("  return response.json();")
        self.lines.append("}")

    def generate_generic(self, node: Node) -> None:
        """
        Fallback: emit a best-effort comment block for any category that
        doesn't yet have a dedicated generator. Keeps the compiler from
        hard-failing when the Dictionary grows faster than the Generator.
        """
        self.lines.append(f"// Unhandled block category '{node.category}':")
        for stmt in node.statements:
            val = f"={stmt.value}" if stmt.value else ""
            self.lines.append(f"//   ({stmt.keyword}{val})")

    # ------------------------------------------------------------------
    def _apply_misc_statement(self, stmt, var_name: str) -> None:
        """Handle keywords that can appear inside almost any block type."""
        kw, val = stmt.keyword, stmt.value

        if kw == "add_css_class" and val:
            self.lines.append(f"if ({var_name}) {var_name}.classList.add('{val}');")
        elif kw == "remove_css_class" and val:
            self.lines.append(f"if ({var_name}) {var_name}.classList.remove('{val}');")
        elif kw == "toggle_css_class" and val:
            self.lines.append(f"if ({var_name}) {var_name}.classList.toggle('{val}');")
        elif kw == "modhtml_element_content" and val:
            self.lines.append(f"if ({var_name}) {var_name}.innerHTML = '{val}';")
        elif kw == "modinline_style" and val:
            prop, _, css_val = val.partition(":")
            if css_val:
                self.lines.append(f"if ({var_name}) {var_name}.style.{prop} = '{css_val}';")
        elif kw == "get_from_os.env" and val:
            self.lines.append(
                f"const {val.lower()} = (window.__VTC_ENV__ || {{}})['{val}'];"
            )
